# Generated by Django 3.2.8 on 2021-10-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_survey',
            name='questions',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etc.question')),
            ],
        ),
        migrations.AddField(
            model_name='completed_survey',
            name='answers',
            field=models.ManyToManyField(to='etc.Answer'),
        ),
    ]
